# Site settings
title: Musings of an Aspiring Developer 
header-img: img/home-bg.png
email: lamia.haider@gmail.com
copyright_name: helianth
description: > # this means to ignore newlines until "baseurl:"
  I might mostly use this to give myself pep talks 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  helianth
learn_profile: helianth
email_username: lamia.haider@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
